version: "3.8"

services:
  flask_app:
    container_name: flask_gemini_api
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: always